@url = http://localhost:3000

POST {{url}}/client

Content-Type: application/json

{
  "firstname": "paul",
  "lastname": "ben",
"phoneNumber": "080123456767",
  "email": "ben@ben.com",
  "password": "ignore"
};